name: Moderate Discussions

on:
  discussion:
    types: [created]
  discussion_comment:
    types: [created]

permissions:
  discussions: write   # close discussions, post comments
  contents: write      # write back to banned.yml / strikes.yml
  actions: write

jobs:
  moderate:
    runs-on: ubuntu-latest
    steps:
      - uses: erstarr/triggerhappy@main # TODO remember to bumb when publishing first stable ver
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # optional - only needed if you move the files elsewhere
          # config_path:  .github/discussion_moderator/config.yml
          # banned_path:  .github/discussion_moderator/banned.yml
          # strikes_path:    .github/discussion_moderator/strikes.yml

          # If you want to enable strikes, specify the number of strikes a user can receive before they are banned
          strikes_to_ban:  3